version: "3.1"
services:
  app:
    image: api
    build: ./
    ports:
      - "8080:8080" # grpc
      - "8082:8082" # http
    volumes:
      - ./:/app
    env_file:
      - .env

  pgsql:
    image: 'postgres:15'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
